version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3006:3006"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: brp
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
